name: Feature request
description: Suggest an improvement to List View
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: Especially helpful for large or multi-page Formidable forms.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
